/* ============================================================
   WordPop — Words for letters G, H, I, J, K
   Generated & reviewed by a multi-agent content workflow.
   Loaded BEFORE data.js. Same shape as LETTER_A.
   ============================================================ */

const LETTER_G = [
  { word: "Good", pos: "describing word", emoji: "👍", say: "GUUD", tier: 1,
    meaning: "Nice and the way it should be.",
    example: "She was a good helper and tidied her toys.",
    synonyms: ["nice", "fine", "kind"], antonyms: ["bad", "mean", "naughty"] },
  { word: "Give", pos: "doing word", emoji: "🎁", say: "GIV", tier: 1,
    meaning: "To hand something to someone.",
    example: "I give my friend a sweet at lunch.",
    synonyms: ["hand", "share", "offer"], antonyms: ["take", "keep", "grab"] },
  { word: "Glad", pos: "describing word", emoji: "😊", say: "GLAD", tier: 1,
    meaning: "Feeling happy about something.",
    example: "I am glad it is a sunny day for play.",
    synonyms: ["happy", "pleased", "cheerful"], antonyms: ["sad", "upset", "unhappy"] },
  { word: "Green", pos: "describing word", emoji: "🟢", say: "GREEN", tier: 1,
    meaning: "The colour of grass and leaves.",
    example: "The frog hid in the green grass.",
    synonyms: ["leafy", "grassy"], antonyms: [] },
  { word: "Grow", pos: "doing word", emoji: "🌱", say: "GROH", tier: 1,
    meaning: "To get bigger as time goes by.",
    example: "My little plant will grow into a tall tree.",
    synonyms: ["rise", "sprout", "spread"], antonyms: ["shrink", "stop"] },
  { word: "Gentle", pos: "describing word", emoji: "🪶", say: "JEN-tul", tier: 2,
    meaning: "Soft and careful, never rough.",
    example: "Be gentle when you hold the tiny kitten.",
    synonyms: ["soft", "kind", "tender"], antonyms: ["rough", "harsh", "hard"] },
  { word: "Giggle", pos: "doing word", emoji: "😄", say: "GIG-ul", tier: 2,
    meaning: "To laugh in a small, silly way.",
    example: "We giggle when the puppy chases its tail.",
    synonyms: ["laugh", "chuckle"], antonyms: ["cry", "sob", "frown"] },
  { word: "Giant", pos: "describing word", emoji: "🦒", say: "JY-unt", tier: 2,
    meaning: "Very, very big.",
    example: "The giant tree was taller than our house.",
    synonyms: ["huge", "enormous", "massive"], antonyms: ["tiny", "small", "little"] },
  { word: "Grin", pos: "doing word", emoji: "😁", say: "GRIN", tier: 2,
    meaning: "To smile a wide, happy smile.",
    example: "He gave a big grin when he won the race.",
    synonyms: ["smile", "beam"], antonyms: ["frown", "scowl", "pout"] },
  { word: "Grab", pos: "doing word", emoji: "✊", say: "GRAB", tier: 2,
    meaning: "To take hold of something quickly.",
    example: "I grab my umbrella before the rain starts.",
    synonyms: ["snatch", "seize", "clutch"], antonyms: ["release", "drop", "let go"] },
  { word: "Gather", pos: "doing word", emoji: "🧺", say: "GA-ther", tier: 3,
    meaning: "To bring things or people together.",
    example: "We gather seashells along the sandy beach.",
    synonyms: ["collect", "group"], antonyms: ["scatter", "spread", "separate"] },
  { word: "Gleam", pos: "doing word", emoji: "✨", say: "GLEEM", tier: 3,
    meaning: "To shine with a bright, happy light.",
    example: "The clean windows gleam in the morning sun.",
    synonyms: ["shine", "sparkle", "glow"], antonyms: ["dull", "dim", "fade"] },
  { word: "Graceful", pos: "describing word", emoji: "🩰", say: "GRAYS-ful", tier: 3,
    meaning: "Moving in a smooth and lovely way.",
    example: "The graceful dancer floated across the stage.",
    synonyms: ["elegant", "smooth", "flowing"], antonyms: ["clumsy", "awkward", "stiff"] },
  { word: "Grumpy", pos: "describing word", emoji: "😠", say: "GRUMP-ee", tier: 3,
    meaning: "Feeling cross and in a bad mood.",
    example: "My brother is grumpy when he wakes up early.",
    synonyms: ["cranky", "moody", "sulky"], antonyms: ["cheerful", "happy", "jolly"] },
  { word: "Grateful", pos: "describing word", emoji: "🙏", say: "GRAYT-ful", tier: 3,
    meaning: "Feeling thankful for something kind.",
    example: "I am grateful for the gift my granny made.",
    synonyms: ["thankful", "pleased"], antonyms: ["ungrateful", "thankless"] },
  { word: "Gigantic", pos: "describing word", emoji: "🐳", say: "jy-GAN-tik", tier: 4,
    meaning: "So huge it is hard to believe.",
    example: "A gigantic whale splashed in the deep blue sea.",
    synonyms: ["enormous", "massive", "huge"], antonyms: ["tiny", "small", "little"] },
  { word: "Generous", pos: "describing word", emoji: "🤲", say: "JEN-ur-us", tier: 4,
    meaning: "Happy to share a lot with others.",
    example: "The generous boy gave half his lunch to a friend.",
    synonyms: ["giving", "kind", "sharing"], antonyms: ["selfish", "stingy", "mean"] },
  { word: "Glisten", pos: "doing word", emoji: "💧", say: "GLIS-un", tier: 4,
    meaning: "To shine softly, like wet things in light.",
    example: "Dewdrops glisten on the spider's silky web.",
    synonyms: ["shimmer", "sparkle"], antonyms: ["dull", "dim", "fade"] },
  { word: "Glide", pos: "doing word", emoji: "🦢", say: "GLYDE", tier: 4,
    meaning: "To move along smoothly and easily.",
    example: "The swan can glide across the calm lake.",
    synonyms: ["slide", "float", "drift"], antonyms: ["stumble", "jerk", "trip"] },
  { word: "Grumble", pos: "doing word", emoji: "😤", say: "GRUM-bul", tier: 4,
    meaning: "To complain in a low, cross voice.",
    example: "He began to grumble about the long, hot walk.",
    synonyms: ["complain", "moan", "mutter"], antonyms: ["praise", "cheer", "rejoice"] },
  { word: "Glorious", pos: "describing word", emoji: "🌅", say: "GLOR-ee-us", tier: 5,
    meaning: "Wonderful and full of beauty.",
    example: "We watched a glorious sunset paint the sky pink.",
    synonyms: ["splendid", "magnificent", "gorgeous"], antonyms: ["dull", "plain", "ordinary"] },
  { word: "Gregarious", pos: "describing word", emoji: "🗣️", say: "gri-GAIR-ee-us", tier: 5,
    meaning: "Loving to be around lots of people.",
    example: "The gregarious girl made friends everywhere she went.",
    synonyms: ["friendly", "sociable", "outgoing"], antonyms: ["shy", "quiet", "lonely"] },
  { word: "Glimmer", pos: "doing word", emoji: "🌟", say: "GLIM-ur", tier: 5,
    meaning: "To shine with a faint, twinkly light.",
    example: "Tiny stars glimmer high above the quiet town.",
    synonyms: ["twinkle", "flicker"], antonyms: ["darken", "dim", "fade"] },
  { word: "Grandeur", pos: "naming word", emoji: "🏰", say: "GRAN-jur", tier: 5,
    meaning: "The grand and splendid look of something big.",
    example: "We gazed at the grandeur of the towering castle.",
    synonyms: ["splendour", "majesty", "glory"], antonyms: [] },
  { word: "Genuine", pos: "describing word", emoji: "💯", say: "JEN-yoo-in", tier: 5,
    meaning: "Real and true, not pretend.",
    example: "She gave a genuine smile that warmed my heart.",
    synonyms: ["real", "true", "honest"], antonyms: ["fake", "false", "pretend"] },
];

const LETTER_H = [
  { word: "Happy", pos: "describing word", emoji: "😊", say: "HAP-ee", tier: 1,
    meaning: "Feeling glad and full of smiles inside.",
    example: "I felt happy when my friend came to play.",
    synonyms: ["glad", "cheerful", "joyful"], antonyms: ["sad", "unhappy", "gloomy"] },
  { word: "Hug", pos: "doing word", emoji: "🤗", say: "HUG", tier: 1,
    meaning: "To hold someone close in your arms with love.",
    example: "Mummy gave me a warm hug before school.",
    synonyms: ["cuddle", "embrace", "squeeze"], antonyms: ["push away", "let go"] },
  { word: "Help", pos: "doing word", emoji: "🤝", say: "HELP", tier: 1,
    meaning: "To do something kind that makes things easier for someone.",
    example: "I help my little sister tie her shoes.",
    synonyms: ["assist", "aid", "support"], antonyms: ["hurt", "bother"] },
  { word: "Hop", pos: "doing word", emoji: "🐰", say: "HOP", tier: 1,
    meaning: "To jump up quickly on one or both feet.",
    example: "The bunny loves to hop across the green grass.",
    synonyms: ["jump", "leap", "bounce"], antonyms: ["sit", "stand still"] },
  { word: "Hand", pos: "naming word", emoji: "✋", say: "HAND", tier: 1,
    meaning: "The part of your body at the end of your arm with fingers.",
    example: "I waved my hand to say hello to Grandpa.",
    synonyms: ["palm", "fist"], antonyms: [] },
  { word: "Hum", pos: "doing word", emoji: "🎵", say: "HUM", tier: 2,
    meaning: "To sing a soft tune with your lips closed.",
    example: "I like to hum my favourite song while I draw.",
    synonyms: ["sing softly", "murmur", "croon"], antonyms: ["shout", "yell"] },
  { word: "Hero", pos: "naming word", emoji: "🦸", say: "HEER-oh", tier: 2,
    meaning: "A brave person who helps others and does good things.",
    example: "The firefighter was a real hero who saved the cat.",
    synonyms: ["champion", "saviour", "star"], antonyms: ["villain", "coward"] },
  { word: "Huge", pos: "describing word", emoji: "🐘", say: "HYOOJ", tier: 2,
    meaning: "Very, very big in size.",
    example: "The elephant was so huge it filled the whole gate.",
    synonyms: ["enormous", "giant", "massive"], antonyms: ["tiny", "small", "little"] },
  { word: "Helpful", pos: "describing word", emoji: "🙋", say: "HELP-ful", tier: 2,
    meaning: "Ready and willing to do kind things for others.",
    example: "My helpful friend carried my heavy bag for me.",
    synonyms: ["kind", "useful", "caring"], antonyms: ["useless", "unkind", "lazy"] },
  { word: "Hungry", pos: "describing word", emoji: "🍽️", say: "HUNG-gree", tier: 2,
    meaning: "Feeling that your tummy wants some food.",
    example: "After playing, I was so hungry I ate two rotis.",
    synonyms: ["peckish", "starving", "famished"], antonyms: ["full", "stuffed", "satisfied"] },
  { word: "Hopeful", pos: "describing word", emoji: "🌈", say: "HOPE-ful", tier: 3,
    meaning: "Feeling that good things will happen soon.",
    example: "I felt hopeful that the rain would stop for our picnic.",
    synonyms: ["positive", "cheerful", "optimistic"], antonyms: ["hopeless", "gloomy", "sad"] },
  { word: "Hide", pos: "doing word", emoji: "🙈", say: "HYDE", tier: 3,
    meaning: "To go somewhere where no one can see you.",
    example: "I like to hide behind the curtain when we play seek.",
    synonyms: ["conceal", "cover", "tuck away"], antonyms: ["show", "reveal", "find"] },
  { word: "Hush", pos: "doing word", emoji: "🤫", say: "HUSH", tier: 3,
    meaning: "To become quiet and still.",
    example: "The baby began to hush when Mummy sang softly.",
    synonyms: ["quieten", "calm", "silence"], antonyms: ["shout", "yell"] },
  { word: "Honest", pos: "describing word", emoji: "💯", say: "ON-ist", tier: 3,
    meaning: "Always telling the truth and never tricking anyone.",
    example: "She was honest and returned the lost coin to her teacher.",
    synonyms: ["truthful", "sincere", "fair"], antonyms: ["dishonest", "lying", "sneaky"] },
  { word: "Hilarious", pos: "describing word", emoji: "😂", say: "hi-LAIR-ee-us", tier: 3,
    meaning: "So funny that it makes you laugh out loud.",
    example: "The clown's silly dance was absolutely hilarious.",
    synonyms: ["funny", "comical", "hysterical"], antonyms: ["boring", "dull", "serious"] },
  { word: "Harmony", pos: "naming word", emoji: "🎶", say: "HAR-muh-nee", tier: 4,
    meaning: "When people or sounds blend together in a happy, peaceful way.",
    example: "The choir sang in beautiful harmony at the show.",
    synonyms: ["peace", "agreement", "balance"], antonyms: ["fighting", "chaos", "clash"] },
  { word: "Heartwarming", pos: "describing word", emoji: "🥰", say: "HART-war-ming", tier: 4,
    meaning: "Something so sweet it fills you with happy, warm feelings.",
    example: "The story of the rescued puppy was heartwarming.",
    synonyms: ["touching", "sweet", "moving"], antonyms: ["upsetting", "sad"] },
  { word: "Hearten", pos: "doing word", emoji: "💪", say: "HAR-ten", tier: 4,
    meaning: "To give someone hope and make them feel braver.",
    example: "The coach's kind words did hearten the tired team.",
    synonyms: ["cheer", "encourage", "comfort"], antonyms: ["discourage", "sadden", "upset"] },
  { word: "Heavenly", pos: "describing word", emoji: "☁️", say: "HEV-un-lee", tier: 4,
    meaning: "So lovely and pleasant that it feels wonderful.",
    example: "The soft, fluffy cake tasted simply heavenly.",
    synonyms: ["lovely", "delightful", "blissful"], antonyms: ["awful", "horrible", "unpleasant"] },
  { word: "Hospitable", pos: "describing word", emoji: "🏡", say: "hoss-PIT-uh-bul", tier: 4,
    meaning: "Warm and welcoming to guests who come to visit.",
    example: "Our hospitable neighbours gave us tea and snacks.",
    synonyms: ["welcoming", "friendly", "kind"], antonyms: ["unwelcoming", "rude", "cold"] },
  { word: "Heartfelt", pos: "describing word", emoji: "💝", say: "HART-felt", tier: 5,
    meaning: "Coming truly and deeply from your heart.",
    example: "She wrote a heartfelt thank-you note to her teacher.",
    synonyms: ["sincere", "genuine", "earnest"], antonyms: ["fake", "insincere"] },
  { word: "Hardy", pos: "describing word", emoji: "🌵", say: "HAR-dee", tier: 5,
    meaning: "Strong and tough enough to handle hard times.",
    example: "The hardy little plant grew even in the dry desert.",
    synonyms: ["tough", "strong", "sturdy"], antonyms: ["weak", "delicate", "fragile"] },
  { word: "Halcyon", pos: "describing word", emoji: "🌅", say: "HAL-see-on", tier: 5,
    meaning: "Calm, peaceful, and happily perfect.",
    example: "We remember those halcyon summer days at the beach.",
    synonyms: ["peaceful", "calm", "blissful"], antonyms: ["stormy", "troubled", "stressful"] },
  { word: "Humdrum", pos: "describing word", emoji: "😑", say: "HUM-drum", tier: 5,
    meaning: "Plain and dull, with nothing fun or new.",
    example: "The rainy day felt humdrum until we built a fort inside.",
    synonyms: ["boring", "dull", "plain"], antonyms: ["exciting", "fun", "lively"] },
  { word: "Humble", pos: "describing word", emoji: "🙇", say: "HUM-bul", tier: 5,
    meaning: "Kind and modest, never showing off how good you are.",
    example: "Even though she won, she stayed humble and thanked her team.",
    synonyms: ["modest", "gentle", "kind"], antonyms: ["boastful", "proud", "showy"] },
];

const LETTER_I = [
  { word: "Ice", pos: "naming word", emoji: "🧊", say: "EYESS", tier: 1,
    meaning: "Water that has frozen hard and cold.",
    example: "I dropped a cube of ice into my glass of juice.",
    synonyms: ["frost", "frozen water"], antonyms: [] },
  { word: "Ill", pos: "describing word", emoji: "🤒", say: "ILL", tier: 1,
    meaning: "Not feeling well in your body.",
    example: "I felt ill, so I stayed home and rested in bed.",
    synonyms: ["sick", "unwell", "poorly"], antonyms: ["well", "healthy", "fine"] },
  { word: "Itch", pos: "doing word", emoji: "🐜", say: "ICH", tier: 1,
    meaning: "To have a tickly feeling on your skin that makes you want to scratch.",
    example: "The mosquito bite made my arm itch all day.",
    synonyms: ["tickle", "tingle", "prickle"], antonyms: [] },
  { word: "Idea", pos: "naming word", emoji: "💡", say: "eye-DEE-uh", tier: 1,
    meaning: "A new thought or plan that pops into your head.",
    example: "I had a great idea for our weekend treasure hunt.",
    synonyms: ["thought", "plan", "notion"], antonyms: [] },
  { word: "Ink", pos: "naming word", emoji: "🖋️", say: "INK", tier: 1,
    meaning: "The colored liquid inside a pen that makes the marks.",
    example: "My pen ran out of ink right in the middle of my drawing.",
    synonyms: ["dye", "writing fluid"], antonyms: [] },
  { word: "Igloo", pos: "naming word", emoji: "🛖", say: "IG-loo", tier: 2,
    meaning: "A round little house built out of blocks of snow and ice.",
    example: "In the story, the polar bear lived in a cozy igloo.",
    synonyms: ["snow house", "ice hut"], antonyms: [] },
  { word: "Island", pos: "naming word", emoji: "🏝️", say: "EYE-land", tier: 2,
    meaning: "A piece of land with water all around it.",
    example: "We sailed our paper boat to the tiny island in the pond.",
    synonyms: ["isle", "key"], antonyms: [] },
  { word: "Itchy", pos: "describing word", emoji: "🦟", say: "ICH-ee", tier: 2,
    meaning: "Feeling tickly and making you want to scratch.",
    example: "My new wool sweater felt itchy on my neck.",
    synonyms: ["scratchy", "tickly", "prickly"], antonyms: ["smooth", "soothing"] },
  { word: "Iron", pos: "doing word", emoji: "👕", say: "EYE-urn", tier: 2,
    meaning: "To press a wrinkled cloth flat with a hot tool.",
    example: "Mom asked me to help iron the wrinkles out of my shirt.",
    synonyms: ["press", "smooth", "flatten"], antonyms: ["wrinkle", "crumple"] },
  { word: "Itchier", pos: "describing word", emoji: "🌿", say: "ICH-ee-ur", tier: 2,
    meaning: "More itchy than something else.",
    example: "The grass made my legs itchier than the sand did.",
    synonyms: ["scratchier", "pricklier"], antonyms: ["smoother", "calmer"] },
  { word: "Improve", pos: "doing word", emoji: "📈", say: "im-PROOV", tier: 3,
    meaning: "To make something better than it was before.",
    example: "I practice every day to improve my handwriting.",
    synonyms: ["better", "upgrade", "boost"], antonyms: ["worsen", "spoil", "ruin"] },
  { word: "Include", pos: "doing word", emoji: "🤝", say: "in-KLOOD", tier: 3,
    meaning: "To let someone or something be part of the group.",
    example: "We always include the new kid in our games at recess.",
    synonyms: ["add", "involve", "count in"], antonyms: ["exclude", "leave out", "skip"] },
  { word: "Invent", pos: "doing word", emoji: "🛠️", say: "in-VENT", tier: 3,
    meaning: "To make something brand new that nobody made before.",
    example: "I want to invent a robot that tidies up my room.",
    synonyms: ["create", "make up", "design"], antonyms: ["copy", "imitate"] },
  { word: "Instant", pos: "describing word", emoji: "⚡", say: "IN-stunt", tier: 3,
    meaning: "Happening right away, in no time at all.",
    example: "The moment I saw the puppy, it was instant love.",
    synonyms: ["immediate", "quick", "sudden"], antonyms: ["slow", "delayed", "gradual"] },
  { word: "Indoor", pos: "describing word", emoji: "🏠", say: "IN-dor", tier: 3,
    meaning: "Made for or happening inside a building.",
    example: "On rainy days we play indoor games like carrom.",
    synonyms: ["inside", "interior", "covered"], antonyms: ["outdoor", "outside", "open-air"] },
  { word: "Imagine", pos: "doing word", emoji: "🌈", say: "ih-MAJ-in", tier: 4,
    meaning: "To make a picture in your mind of something not really there.",
    example: "I like to imagine that my bed is a pirate ship.",
    synonyms: ["dream", "picture", "pretend"], antonyms: ["forget", "ignore"] },
  { word: "Incredible", pos: "describing word", emoji: "🤯", say: "in-KRED-uh-bul", tier: 4,
    meaning: "So amazing that it is almost too good to believe.",
    example: "The magician's trick was so incredible that we all gasped.",
    synonyms: ["amazing", "unbelievable", "astonishing"], antonyms: ["ordinary", "boring", "dull"] },
  { word: "Important", pos: "describing word", emoji: "⭐", say: "im-POR-tunt", tier: 4,
    meaning: "Mattering a lot and worth caring about.",
    example: "It is important to brush your teeth every night.",
    synonyms: ["needed", "big", "essential"], antonyms: ["unimportant", "minor", "trivial"] },
  { word: "Invisible", pos: "describing word", emoji: "👻", say: "in-VIZ-uh-bul", tier: 4,
    meaning: "Cannot be seen by your eyes at all.",
    example: "I wished I had an invisible cloak to play hide-and-seek.",
    synonyms: ["unseen", "hidden", "see-through"], antonyms: ["visible", "seen", "clear"] },
  { word: "Independent", pos: "describing word", emoji: "🦸", say: "in-dee-PEN-dunt", tier: 4,
    meaning: "Able to do things by yourself without help.",
    example: "My little sister is independent now and ties her own shoes.",
    synonyms: ["self-reliant", "free", "capable"], antonyms: ["dependent", "helpless", "needy"] },
  { word: "Inspire", pos: "doing word", emoji: "✨", say: "in-SPYRE", tier: 5,
    meaning: "To fill someone with a happy wish to try or do something.",
    example: "My teacher's story did inspire me to write my own book.",
    synonyms: ["encourage", "motivate", "spark"], antonyms: ["discourage", "bore", "dishearten"] },
  { word: "Immense", pos: "describing word", emoji: "🐋", say: "ih-MENSS", tier: 5,
    meaning: "Very, very big in size or amount.",
    example: "The blue whale is an immense creature of the deep sea.",
    synonyms: ["huge", "gigantic", "enormous"], antonyms: ["tiny", "small", "little"] },
  { word: "Inquisitive", pos: "describing word", emoji: "🔍", say: "in-KWIZ-uh-tiv", tier: 5,
    meaning: "Always wanting to learn and ask lots of questions.",
    example: "My inquisitive cousin asks why the sky is blue.",
    synonyms: ["curious", "questioning", "interested"], antonyms: ["uninterested", "bored", "indifferent"] },
  { word: "Illuminate", pos: "doing word", emoji: "🔦", say: "ih-LOO-mih-nayt", tier: 5,
    meaning: "To shine light on something so it can be seen.",
    example: "We used a torch to illuminate the dark cave path.",
    synonyms: ["light up", "brighten", "glow"], antonyms: ["darken", "dim", "shadow"] },
  { word: "Immaculate", pos: "describing word", emoji: "🧼", say: "ih-MAK-yuh-lut", tier: 5,
    meaning: "Perfectly clean with not a single spot or mess.",
    example: "After hours of tidying, my room looked immaculate.",
    synonyms: ["spotless", "clean", "tidy"], antonyms: ["dirty", "messy", "filthy"] },
];

const LETTER_J = [
  { word: "Jump", pos: "doing word", emoji: "🤸", say: "JUMP", tier: 1,
    meaning: "To push off the ground with your legs and go up into the air.",
    example: "I love to jump high on the bouncy trampoline.",
    synonyms: ["leap", "hop", "bounce"], antonyms: ["sit", "crouch", "land"] },
  { word: "Join", pos: "doing word", emoji: "🤝", say: "JOYN", tier: 1,
    meaning: "To come together with others or put things together.",
    example: "Come and join us for a fun game of tag!",
    synonyms: ["connect", "unite", "link"], antonyms: ["leave", "split", "separate"] },
  { word: "Jar", pos: "naming word", emoji: "🫙", say: "JAR", tier: 1,
    meaning: "A round glass pot with a wide top for keeping things.",
    example: "Mum filled the jar with sweet homemade jam.",
    synonyms: ["pot", "container", "tub"], antonyms: [] },
  { word: "Jacket", pos: "naming word", emoji: "🧥", say: "JAK-it", tier: 1,
    meaning: "A short warm coat you wear on your top half.",
    example: "I zipped up my jacket before going out in the cold.",
    synonyms: ["coat", "blazer", "top"], antonyms: [] },
  { word: "Juice", pos: "naming word", emoji: "🧃", say: "JOOS", tier: 1,
    meaning: "The sweet drink that comes out of fruits.",
    example: "I had a glass of cold orange juice with breakfast.",
    synonyms: ["drink", "squash", "nectar"], antonyms: [] },
  { word: "Jolly", pos: "describing word", emoji: "😄", say: "JOL-ee", tier: 2,
    meaning: "Feeling happy and full of cheer.",
    example: "Grandpa is so jolly when he tells funny stories.",
    synonyms: ["cheerful", "merry", "happy"], antonyms: ["grumpy", "sad", "gloomy"] },
  { word: "Juicy", pos: "describing word", emoji: "🍊", say: "JOO-see", tier: 2,
    meaning: "Full of yummy liquid that drips when you bite it.",
    example: "The juicy mango ran down my chin as I ate it.",
    synonyms: ["wet", "moist", "dripping"], antonyms: ["dry", "crisp"] },
  { word: "Jiggle", pos: "doing word", emoji: "🍮", say: "JIG-uhl", tier: 2,
    meaning: "To shake or wobble with quick little movements.",
    example: "The jelly began to jiggle when I poked it.",
    synonyms: ["wobble", "shake", "wiggle"], antonyms: ["still", "steady", "freeze"] },
  { word: "Jog", pos: "doing word", emoji: "🏃", say: "JOG", tier: 2,
    meaning: "To run at a slow and easy speed.",
    example: "We jog around the park every morning before school.",
    synonyms: ["run", "trot", "scamper"], antonyms: ["walk", "stop", "rest"] },
  { word: "Joke", pos: "naming word", emoji: "🤣", say: "JOHK", tier: 2,
    meaning: "A funny thing you say to make people laugh.",
    example: "My sister told a silly joke and we all giggled.",
    synonyms: ["gag", "jest", "wisecrack"], antonyms: [] },
  { word: "Jingle", pos: "doing word", emoji: "🔔", say: "JING-guhl", tier: 3,
    meaning: "To make a soft ringing sound like little bells.",
    example: "The coins in my pocket jingle when I walk.",
    synonyms: ["ring", "chime", "tinkle"], antonyms: ["hush", "silence"] },
  { word: "Jewel", pos: "naming word", emoji: "💎", say: "JOO-uhl", tier: 3,
    meaning: "A shiny, pretty stone that sparkles in the light.",
    example: "The crown was covered with a sparkling blue jewel.",
    synonyms: ["gem", "stone", "diamond"], antonyms: [] },
  { word: "Journey", pos: "naming word", emoji: "🧳", say: "JUR-nee", tier: 3,
    meaning: "A long trip from one place to another.",
    example: "Our journey to the hills took us through tunnels and bridges.",
    synonyms: ["trip", "voyage", "travel"], antonyms: [] },
  { word: "Joyful", pos: "describing word", emoji: "😁", say: "JOY-ful", tier: 3,
    meaning: "Feeling very, very happy inside.",
    example: "The whole class felt joyful when the picnic began.",
    synonyms: ["happy", "glad", "delighted"], antonyms: ["sad", "miserable", "gloomy"] },
  { word: "Jolt", pos: "doing word", emoji: "⚡", say: "JOHLT", tier: 3,
    meaning: "To suddenly shake or move with a quick bump.",
    example: "The bus made me jolt forward when it stopped fast.",
    synonyms: ["jerk", "bump", "lurch"], antonyms: ["glide", "ease", "drift"] },
  { word: "Jumble", pos: "doing word", emoji: "🧩", say: "JUM-buhl", tier: 4,
    meaning: "To mix things up into an untidy muddle.",
    example: "My toys jumble together in a big messy pile.",
    synonyms: ["mix", "muddle", "scramble"], antonyms: ["sort", "arrange", "tidy"] },
  { word: "Jagged", pos: "describing word", emoji: "⛰️", say: "JAG-id", tier: 4,
    meaning: "Having sharp, pointy, uneven edges.",
    example: "The jagged rocks felt rough and pointy under my feet.",
    synonyms: ["sharp", "rough", "spiky"], antonyms: ["smooth", "even", "flat"] },
  { word: "Jittery", pos: "describing word", emoji: "😬", say: "JIT-uh-ree", tier: 4,
    meaning: "Feeling shaky and nervous inside.",
    example: "I felt jittery before standing up to sing on stage.",
    synonyms: ["nervous", "shaky", "jumpy"], antonyms: ["calm", "relaxed", "steady"] },
  { word: "Juggle", pos: "doing word", emoji: "🤹", say: "JUG-uhl", tier: 4,
    meaning: "To keep tossing and catching many things in the air at once.",
    example: "The clown can juggle three balls without dropping one.",
    synonyms: ["toss", "throw", "flip"], antonyms: ["drop", "fumble"] },
  { word: "Jab", pos: "doing word", emoji: "👉", say: "JAB", tier: 4,
    meaning: "To poke something quickly and sharply.",
    example: "I gave the soft pillow a quick jab with my finger.",
    synonyms: ["poke", "prod", "nudge"], antonyms: ["pat", "stroke", "caress"] },
  { word: "Jovial", pos: "describing word", emoji: "🥳", say: "JOH-vee-uhl", tier: 5,
    meaning: "Warm, friendly, and bursting with good cheer.",
    example: "Our jovial uncle laughs loudly and hugs everyone at the party.",
    synonyms: ["cheerful", "merry", "jolly"], antonyms: ["grumpy", "gloomy", "sullen"] },
  { word: "Jubilant", pos: "describing word", emoji: "🎉", say: "JOO-bih-luhnt", tier: 5,
    meaning: "So happy that you want to cheer and celebrate.",
    example: "The team was jubilant when they won the big match.",
    synonyms: ["thrilled", "overjoyed", "elated"], antonyms: ["sad", "downcast", "glum"] },
  { word: "Jaunty", pos: "describing word", emoji: "🎩", say: "JAWN-tee", tier: 5,
    meaning: "Cheerful and lively, in a bright and bouncy way.",
    example: "He walked in with a jaunty hop, whistling a happy tune.",
    synonyms: ["lively", "perky", "sprightly"], antonyms: ["dull", "gloomy", "tired"] },
  { word: "Jubilee", pos: "naming word", emoji: "🎊", say: "JOO-bih-lee", tier: 5,
    meaning: "A big, happy celebration for something special.",
    example: "The town held a jubilee with music and dancing in the street.",
    synonyms: ["celebration", "festival", "party"], antonyms: [] },
  { word: "Justice", pos: "naming word", emoji: "⚖️", say: "JUS-tiss", tier: 5,
    meaning: "Being fair, so everyone is treated in the right way.",
    example: "The teacher cared about justice and gave both children a fair turn.",
    synonyms: ["fairness", "rightness", "honesty"], antonyms: ["unfairness", "wrong"] },
];

const LETTER_K = [
  { word: "Kind", pos: "describing word", emoji: "🤗", say: "KYND", tier: 1,
    meaning: "Caring and gentle to other people.",
    example: "She was kind and shared her lunch with the new boy.",
    synonyms: ["caring", "gentle", "nice"], antonyms: ["mean", "cruel", "unkind"] },
  { word: "Keep", pos: "doing word", emoji: "🤲", say: "KEEP", tier: 1,
    meaning: "To hold on to something and not let it go.",
    example: "You can keep the shiny pebble you found at the beach.",
    synonyms: ["hold", "save", "store"], antonyms: ["lose", "give", "drop"] },
  { word: "King", pos: "naming word", emoji: "👑", say: "KING", tier: 1,
    meaning: "A man who rules a whole country.",
    example: "The king sat on his golden throne in the big castle.",
    synonyms: ["ruler", "monarch", "lord"], antonyms: [] },
  { word: "Key", pos: "naming word", emoji: "🔑", say: "KEE", tier: 1,
    meaning: "A small metal piece that opens a lock.",
    example: "Mum used the key to open our front door.",
    synonyms: ["opener", "unlocker"], antonyms: [] },
  { word: "Kick", pos: "doing word", emoji: "⚽", say: "KIK", tier: 1,
    meaning: "To hit something hard with your foot.",
    example: "He gave the ball a big kick into the goal.",
    synonyms: ["boot", "punt", "strike"], antonyms: [] },
  { word: "Kitten", pos: "naming word", emoji: "🐱", say: "KIT-en", tier: 2,
    meaning: "A baby cat.",
    example: "The tiny kitten curled up and fell asleep on my lap.",
    synonyms: ["cat", "kitty"], antonyms: [] },
  { word: "Kettle", pos: "naming word", emoji: "🫖", say: "KET-ul", tier: 2,
    meaning: "A pot used to boil water for tea.",
    example: "The kettle began to whistle when the water was hot.",
    synonyms: ["pot", "boiler"], antonyms: [] },
  { word: "Knock", pos: "doing word", emoji: "✊", say: "NOK", tier: 2,
    meaning: "To tap on a door so people know you are there.",
    example: "Please knock before you come into my room.",
    synonyms: ["tap", "rap", "bang"], antonyms: [] },
  { word: "Knit", pos: "doing word", emoji: "🧶", say: "NIT", tier: 2,
    meaning: "To make cloth by looping wool with two needles.",
    example: "Grandma likes to knit warm socks in the winter.",
    synonyms: ["weave", "loop", "sew"], antonyms: [] },
  { word: "Kneel", pos: "doing word", emoji: "🧎", say: "NEEL", tier: 2,
    meaning: "To go down and rest on your knees.",
    example: "I had to kneel down to tie my little sister's shoe.",
    synonyms: ["crouch", "stoop", "bow"], antonyms: ["stand", "rise"] },
  { word: "Keen", pos: "describing word", emoji: "😃", say: "KEEN", tier: 3,
    meaning: "Very excited and wanting to do something.",
    example: "He was keen to start his new painting right away.",
    synonyms: ["eager", "excited", "ready"], antonyms: ["bored", "unwilling", "lazy"] },
  { word: "Kingdom", pos: "naming word", emoji: "🏰", say: "KING-dum", tier: 3,
    meaning: "A land that a king or queen rules over.",
    example: "The whole kingdom cheered when the princess came home.",
    synonyms: ["realm", "land", "empire"], antonyms: [] },
  { word: "Knot", pos: "naming word", emoji: "🪢", say: "NOT", tier: 3,
    meaning: "A tight twist where you tie something together.",
    example: "I tied a knot so my balloon would not float away.",
    synonyms: ["tie", "loop", "bow"], antonyms: [] },
  { word: "Kitchen", pos: "naming word", emoji: "🍳", say: "KIT-chin", tier: 3,
    meaning: "The room in a house where you cook food.",
    example: "Yummy smells drifted out of the kitchen at dinnertime.",
    synonyms: ["cookhouse", "galley"], antonyms: [] },
  { word: "Kindle", pos: "doing word", emoji: "🔥", say: "KIN-dul", tier: 3,
    meaning: "To start a small fire.",
    example: "The campers tried to kindle a fire with dry sticks.",
    synonyms: ["light", "spark", "ignite"], antonyms: ["douse", "put out"] },
  { word: "Kindly", pos: "describing word", emoji: "😊", say: "KYND-lee", tier: 4,
    meaning: "Warm and caring in the way you act.",
    example: "The kindly old man helped us cross the busy road.",
    synonyms: ["gentle", "warm", "caring"], antonyms: ["harsh", "unkind", "cruel"] },
  { word: "Keepsake", pos: "naming word", emoji: "🎁", say: "KEEP-sayk", tier: 4,
    meaning: "A special little thing you save to remember someone.",
    example: "She kept the seashell as a keepsake from our trip.",
    synonyms: ["memento", "souvenir", "treasure"], antonyms: [] },
  { word: "Knack", pos: "naming word", emoji: "✨", say: "NAK", tier: 4,
    meaning: "A clever skill for doing something well.",
    example: "He has a real knack for telling funny jokes.",
    synonyms: ["talent", "skill", "gift"], antonyms: [] },
  { word: "Kernel", pos: "naming word", emoji: "🌽", say: "KUR-nul", tier: 4,
    meaning: "A tiny seed or grain, like one bit of corn.",
    example: "A single popcorn kernel popped right out of the bowl.",
    synonyms: ["seed", "grain", "pip"], antonyms: [] },
  { word: "Keeper", pos: "naming word", emoji: "🦒", say: "KEEP-er", tier: 4,
    meaning: "A person who looks after animals or important things.",
    example: "The zoo keeper feeds the giraffes every morning.",
    synonyms: ["guardian", "minder", "carer"], antonyms: [] },
  { word: "Kindhearted", pos: "describing word", emoji: "💗", say: "KYND-har-tid", tier: 5,
    meaning: "Full of warmth and love for other people.",
    example: "The kindhearted girl gave her umbrella to a wet stranger.",
    synonyms: ["caring", "loving", "gentle"], antonyms: ["cruel", "heartless", "mean"] },
  { word: "Knowledgeable", pos: "describing word", emoji: "🧠", say: "NOL-ij-uh-bul", tier: 5,
    meaning: "Knowing a great deal about many things.",
    example: "Our teacher is so knowledgeable about dinosaurs.",
    synonyms: ["clever", "wise", "learned"], antonyms: ["clueless", "unaware"] },
  { word: "Kindness", pos: "naming word", emoji: "💞", say: "KYND-nis", tier: 5,
    meaning: "The warm and caring way you treat other people.",
    example: "Her kindness made the lonely new girl feel welcome.",
    synonyms: ["care", "warmth", "goodness"], antonyms: ["cruelty", "meanness", "harshness"] },
  { word: "Kaleidoscope", pos: "naming word", emoji: "🔮", say: "kuh-LY-duh-skohp", tier: 5,
    meaning: "A tube you look in to see colourful changing shapes.",
    example: "I twisted the kaleidoscope and the colours danced like magic.",
    synonyms: ["viewer", "tube"], antonyms: [] },
  { word: "Kaleidoscopic", pos: "describing word", emoji: "🌈", say: "kuh-ly-duh-SKOP-ik", tier: 5,
    meaning: "Full of many bright, ever-changing colours.",
    example: "The festival lights made the whole street look kaleidoscopic.",
    synonyms: ["colourful", "vivid", "bright"], antonyms: ["dull", "plain", "grey"] },
];

