/* ============================================================
   WordPop — Words for letters B, C, D, E, F
   Generated & reviewed by a multi-agent content workflow.
   Loaded BEFORE data.js so these arrays are available there.
   Edit freely — same shape as LETTER_A in data.js.
   ============================================================ */

const LETTER_B = [
  { word: "Ball", pos: "naming word", emoji: "⚽", say: "BAWL", tier: 1,
    meaning: "A round toy you can throw, kick, or bounce.",
    example: "We kicked the ball across the playground at recess.",
    synonyms: ["sphere"], antonyms: [] },
  { word: "Big", pos: "describing word", emoji: "🐘", say: "BIG", tier: 1,
    meaning: "Larger in size than other things.",
    example: "The elephant at the zoo was big and gray.",
    synonyms: ["large", "huge", "giant"], antonyms: ["small", "tiny", "little"] },
  { word: "Blue", pos: "describing word", emoji: "🔵", say: "BLOO", tier: 1,
    meaning: "The color of the clear sky and the deep sea.",
    example: "I painted the ocean blue in my picture.",
    synonyms: ["sky-colored"], antonyms: [] },
  { word: "Bird", pos: "naming word", emoji: "🐦", say: "BURD", tier: 1,
    meaning: "An animal with feathers and wings that can fly.",
    example: "A little bird sang on the branch this morning.",
    synonyms: ["sparrow", "creature"], antonyms: [] },
  { word: "Box", pos: "naming word", emoji: "📦", say: "BOKS", tier: 1,
    meaning: "A container with flat sides for holding things.",
    example: "I kept all my crayons in a small box.",
    synonyms: ["carton", "case"], antonyms: [] },
  { word: "Brave", pos: "describing word", emoji: "🦁", say: "BRAYV", tier: 2,
    meaning: "Not afraid to do hard or scary things.",
    example: "She was brave and went down the tall slide.",
    synonyms: ["bold", "fearless", "daring"], antonyms: ["scared", "afraid", "timid"] },
  { word: "Bright", pos: "describing word", emoji: "☀️", say: "BRYT", tier: 2,
    meaning: "Full of light, or very clever.",
    example: "The bright sun made me cover my eyes.",
    synonyms: ["shiny", "glowing", "clever"], antonyms: ["dim", "dull", "dark"] },
  { word: "Build", pos: "doing word", emoji: "🧱", say: "BILD", tier: 2,
    meaning: "To make something by putting parts together.",
    example: "We can build a tall tower with these blocks.",
    synonyms: ["make", "construct"], antonyms: ["break", "destroy", "wreck"] },
  { word: "Begin", pos: "doing word", emoji: "🏁", say: "bee-GIN", tier: 2,
    meaning: "To start doing something.",
    example: "Let's begin the game when everyone is ready.",
    synonyms: ["start", "commence"], antonyms: ["end", "finish", "stop"] },
  { word: "Bounce", pos: "doing word", emoji: "🏀", say: "BOWNSS", tier: 2,
    meaning: "To spring back up after hitting the ground.",
    example: "Watch the ball bounce high off the floor.",
    synonyms: ["spring", "hop", "rebound"], antonyms: [] },
  { word: "Beautiful", pos: "describing word", emoji: "🌸", say: "BYOO-ti-ful", tier: 3,
    meaning: "So lovely that it makes you happy to look at.",
    example: "The garden was full of beautiful pink flowers.",
    synonyms: ["pretty", "lovely", "gorgeous"], antonyms: ["ugly", "plain"] },
  { word: "Brilliant", pos: "describing word", emoji: "💡", say: "BRIL-yunt", tier: 3,
    meaning: "Very, very smart or shining very bright.",
    example: "My friend had a brilliant idea for our project.",
    synonyms: ["clever", "smart", "dazzling"], antonyms: ["dull", "foolish", "silly"] },
  { word: "Busy", pos: "describing word", emoji: "🐝", say: "BIZ-ee", tier: 3,
    meaning: "Having lots of things to do.",
    example: "The busy bees buzzed from flower to flower.",
    synonyms: ["active", "occupied"], antonyms: ["idle", "lazy", "free"] },
  { word: "Borrow", pos: "doing word", emoji: "🤲", say: "BOR-oh", tier: 3,
    meaning: "To take something for a while and give it back later.",
    example: "May I borrow your pencil until lunchtime?",
    synonyms: ["take", "use"], antonyms: ["lend", "give", "loan"] },
  { word: "Brisk", pos: "describing word", emoji: "🚶", say: "BRISK", tier: 3,
    meaning: "Quick and full of energy.",
    example: "We took a brisk walk to warm up in the cold.",
    synonyms: ["quick", "speedy", "lively"], antonyms: ["slow", "lazy", "sluggish"] },
  { word: "Balance", pos: "doing word", emoji: "🤸", say: "BAL-unss", tier: 4,
    meaning: "To stay steady without falling over.",
    example: "I can balance on one foot like a flamingo.",
    synonyms: ["steady", "poise"], antonyms: ["wobble", "topple", "fall"] },
  { word: "Bashful", pos: "describing word", emoji: "😳", say: "BASH-ful", tier: 4,
    meaning: "Shy and a little embarrassed around others.",
    example: "He felt bashful when the whole class clapped for him.",
    synonyms: ["shy", "timid", "coy"], antonyms: ["bold", "confident", "outgoing"] },
  { word: "Blossom", pos: "doing word", emoji: "🌼", say: "BLOSS-um", tier: 4,
    meaning: "To grow flowers, or to grow better and better.",
    example: "The cherry tree began to blossom in spring.",
    synonyms: ["bloom", "flower", "flourish"], antonyms: ["wither", "fade", "wilt"] },
  { word: "Bewilder", pos: "doing word", emoji: "😵‍💫", say: "bee-WIL-der", tier: 4,
    meaning: "To confuse someone so much they don't know what to do.",
    example: "The tricky maze began to bewilder the puppy.",
    synonyms: ["confuse", "puzzle", "baffle"], antonyms: ["explain", "clarify", "guide"] },
  { word: "Brittle", pos: "describing word", emoji: "🍂", say: "BRIT-ul", tier: 4,
    meaning: "Easy to snap or break into pieces.",
    example: "The dry leaf was so brittle it crumbled in my hand.",
    synonyms: ["fragile", "crumbly", "delicate"], antonyms: ["sturdy", "tough", "strong"] },
  { word: "Boisterous", pos: "describing word", emoji: "🎉", say: "BOY-stuh-rus", tier: 5,
    meaning: "Very loud, lively, and full of cheerful noise.",
    example: "The boisterous crowd cheered for the school team.",
    synonyms: ["rowdy", "lively", "noisy"], antonyms: ["quiet", "calm", "peaceful"] },
  { word: "Benevolent", pos: "describing word", emoji: "🤗", say: "buh-NEV-uh-lunt", tier: 5,
    meaning: "Kind and wanting to help others.",
    example: "The benevolent old man shared his lunch with us.",
    synonyms: ["kind", "caring", "generous"], antonyms: ["cruel", "mean", "selfish"] },
  { word: "Bountiful", pos: "describing word", emoji: "🧺", say: "BOWN-ti-ful", tier: 5,
    meaning: "More than enough; a very large amount.",
    example: "The farmer had a bountiful basket of fresh fruit.",
    synonyms: ["plentiful", "abundant", "generous"], antonyms: ["scarce", "meager", "empty"] },
  { word: "Bewitching", pos: "describing word", emoji: "✨", say: "bee-WICH-ing", tier: 5,
    meaning: "So charming and lovely it seems almost magical.",
    example: "The dancer wore a bewitching, sparkly costume.",
    synonyms: ["charming", "enchanting", "captivating"], antonyms: ["dull", "plain", "boring"] },
  { word: "Burgeon", pos: "doing word", emoji: "🌱", say: "BUR-jun", tier: 5,
    meaning: "To grow and spread very quickly.",
    example: "Tiny seeds began to burgeon into a leafy plant.",
    synonyms: ["grow", "flourish", "bloom"], antonyms: ["shrink", "wither", "fade"] },
];

const LETTER_C = [
  { word: "Cat", pos: "naming word", emoji: "🐱", say: "KAT", tier: 1,
    meaning: "A soft, furry pet that says meow and likes to nap.",
    example: "My cat curled up on my lap and purred all afternoon.",
    synonyms: ["kitty", "kitten"], antonyms: [] },
  { word: "Cup", pos: "naming word", emoji: "☕", say: "KUP", tier: 1,
    meaning: "A small open container you drink from.",
    example: "I filled my cup with warm milk before bed.",
    synonyms: ["mug", "tumbler"], antonyms: [] },
  { word: "Cake", pos: "naming word", emoji: "🍰", say: "KAYK", tier: 1,
    meaning: "A soft, sweet treat we eat on birthdays.",
    example: "We sang happy birthday and cut the chocolate cake.",
    synonyms: ["dessert", "treat"], antonyms: [] },
  { word: "Cold", pos: "describing word", emoji: "🥶", say: "KOHLD", tier: 1,
    meaning: "Having a low temperature, not warm at all.",
    example: "The ice cream felt cold on my tongue.",
    synonyms: ["chilly", "icy", "cool"], antonyms: ["hot", "warm"] },
  { word: "Clap", pos: "doing word", emoji: "👏", say: "KLAP", tier: 1,
    meaning: "To hit your hands together to make a happy sound.",
    example: "We all clap when the puppet show is over.",
    synonyms: ["applaud", "cheer"], antonyms: [] },
  { word: "Climb", pos: "doing word", emoji: "🧗", say: "KLYM", tier: 2,
    meaning: "To go up something using your hands and feet.",
    example: "I love to climb the ladder up to the slide.",
    synonyms: ["scale", "ascend", "clamber"], antonyms: ["descend", "fall"] },
  { word: "Clever", pos: "describing word", emoji: "🧠", say: "KLEV-er", tier: 2,
    meaning: "Quick to learn and good at figuring things out.",
    example: "My clever puppy learned how to open the toy box.",
    synonyms: ["smart", "bright", "sharp"], antonyms: ["silly", "foolish"] },
  { word: "Calm", pos: "describing word", emoji: "😌", say: "KAHM", tier: 2,
    meaning: "Quiet and peaceful, with no worry inside.",
    example: "The lake was so calm that it looked like glass.",
    synonyms: ["peaceful", "quiet", "relaxed"], antonyms: ["wild", "stormy", "upset"] },
  { word: "Catch", pos: "doing word", emoji: "🧤", say: "KACH", tier: 2,
    meaning: "To grab something flying or thrown to you.",
    example: "Try to catch the ball when I toss it to you!",
    synonyms: ["grab", "snatch", "seize"], antonyms: ["drop", "throw", "release"] },
  { word: "Cozy", pos: "describing word", emoji: "🛌", say: "KOH-zee", tier: 2,
    meaning: "Warm, soft, and comfy in a happy way.",
    example: "I felt cozy under my fluffy blanket on a rainy day.",
    synonyms: ["snug", "comfy", "warm"], antonyms: ["cold", "uncomfortable"] },
  { word: "Curious", pos: "describing word", emoji: "🤔", say: "KYOOR-ee-us", tier: 3,
    meaning: "Wanting to learn and find out new things.",
    example: "The curious kitten peeked inside every open drawer.",
    synonyms: ["interested", "inquisitive", "nosy"], antonyms: ["bored", "uninterested"] },
  { word: "Cheerful", pos: "describing word", emoji: "😄", say: "CHEER-ful", tier: 3,
    meaning: "Full of smiles and happy feelings.",
    example: "Her cheerful song made the whole class giggle.",
    synonyms: ["happy", "jolly", "merry"], antonyms: ["sad", "gloomy", "grumpy"] },
  { word: "Create", pos: "doing word", emoji: "🎨", say: "kree-AYT", tier: 3,
    meaning: "To make something brand new.",
    example: "I love to create little animals out of soft clay.",
    synonyms: ["make", "build", "invent"], antonyms: ["destroy", "wreck"] },
  { word: "Capture", pos: "doing word", emoji: "📸", say: "KAP-cher", tier: 3,
    meaning: "To catch and hold onto something or someone.",
    example: "I tried to capture the firefly gently in my jar.",
    synonyms: ["catch", "trap", "grab"], antonyms: ["release", "free", "let go"] },
  { word: "Crunchy", pos: "describing word", emoji: "🥕", say: "KRUN-chee", tier: 3,
    meaning: "Hard and noisy when you bite it.",
    example: "The crunchy carrot went snap in my mouth.",
    synonyms: ["crispy", "crackly"], antonyms: ["soft", "soggy", "mushy"] },
  { word: "Confident", pos: "describing word", emoji: "💪", say: "KON-fih-dent", tier: 4,
    meaning: "Sure that you can do something well.",
    example: "She felt confident before her big spelling test.",
    synonyms: ["sure", "bold", "brave"], antonyms: ["shy", "unsure", "scared"] },
  { word: "Cautious", pos: "describing word", emoji: "🚸", say: "KAW-shus", tier: 4,
    meaning: "Being careful so nothing goes wrong.",
    example: "Be cautious when you cross the busy road.",
    synonyms: ["careful", "watchful", "alert"], antonyms: ["careless", "reckless"] },
  { word: "Comfort", pos: "doing word", emoji: "🤗", say: "KUM-fert", tier: 4,
    meaning: "To make someone feel better and safe.",
    example: "I hugged my friend to comfort her when she cried.",
    synonyms: ["soothe", "calm", "cheer"], antonyms: ["upset", "hurt", "worry"] },
  { word: "Conquer", pos: "doing word", emoji: "🏔️", say: "KON-ker", tier: 4,
    meaning: "To beat a big problem or fear with effort.",
    example: "He worked hard to conquer his fear of the deep pool.",
    synonyms: ["beat", "overcome", "defeat"], antonyms: ["lose", "surrender", "give up"] },
  { word: "Cuddle", pos: "doing word", emoji: "🧸", say: "KUD-ul", tier: 4,
    meaning: "To hold someone close in a warm, soft hug.",
    example: "I cuddle my teddy bear every single night.",
    synonyms: ["hug", "snuggle", "embrace"], antonyms: ["push away", "let go"] },
  { word: "Courageous", pos: "describing word", emoji: "🦁", say: "kuh-RAY-jus", tier: 5,
    meaning: "Very brave, even when something feels scary.",
    example: "The courageous girl spoke up in front of the whole school.",
    synonyms: ["brave", "bold", "fearless"], antonyms: ["timid", "cowardly", "afraid"] },
  { word: "Compassionate", pos: "describing word", emoji: "💗", say: "kum-PASH-un-it", tier: 5,
    meaning: "Kind and caring about how others feel.",
    example: "My compassionate brother shared his lunch with a hungry pup.",
    synonyms: ["kind", "caring", "gentle"], antonyms: ["cruel", "mean", "heartless"] },
  { word: "Captivating", pos: "describing word", emoji: "✨", say: "KAP-tih-vay-ting", tier: 5,
    meaning: "So interesting that you cannot look away.",
    example: "The magician's captivating trick made us all gasp.",
    synonyms: ["fascinating", "charming", "enchanting"], antonyms: ["boring", "dull"] },
  { word: "Cherish", pos: "doing word", emoji: "💝", say: "CHAIR-ish", tier: 5,
    meaning: "To love something so much that you keep it safe.",
    example: "I cherish the friendship bracelet my best friend made me.",
    synonyms: ["treasure", "adore", "love"], antonyms: ["ignore", "neglect"] },
  { word: "Conscientious", pos: "describing word", emoji: "📝", say: "kon-shee-EN-shus", tier: 5,
    meaning: "Careful to do your work well and the right way.",
    example: "The conscientious student checked every answer twice.",
    synonyms: ["careful", "thorough", "diligent"], antonyms: ["careless", "lazy", "sloppy"] },
];

const LETTER_D = [
  { word: "Dog", pos: "naming word", emoji: "🐶", say: "DAWG", tier: 1,
    meaning: "A furry, friendly animal that many people keep as a pet.",
    example: "My dog wagged his tail when I came home from school.",
    synonyms: ["puppy", "pup"], antonyms: [] },
  { word: "Door", pos: "naming word", emoji: "🚪", say: "DOR", tier: 1,
    meaning: "The part you open and close to go in or out of a room.",
    example: "I knocked on the door before going into the kitchen.",
    synonyms: ["gate", "entrance"], antonyms: [] },
  { word: "Draw", pos: "doing word", emoji: "✏️", say: "DRAW", tier: 1,
    meaning: "To make a picture with a pencil, pen, or crayon.",
    example: "I love to draw a big yellow sun in the corner of my page.",
    synonyms: ["sketch", "doodle"], antonyms: ["erase"] },
  { word: "Dry", pos: "describing word", emoji: "🏜️", say: "DRY", tier: 1,
    meaning: "Not wet at all, with no water on it.",
    example: "I rubbed my hair dry with a soft towel after my bath.",
    synonyms: ["crisp", "waterless"], antonyms: ["wet", "damp", "soggy"] },
  { word: "Dirty", pos: "describing word", emoji: "🧦", say: "DUR-tee", tier: 1,
    meaning: "Covered in mud, dust, or spots that need washing.",
    example: "My shoes were dirty after I played in the muddy garden.",
    synonyms: ["mucky", "messy", "grubby"], antonyms: ["clean", "spotless"] },
  { word: "Dance", pos: "doing word", emoji: "💃", say: "DANSS", tier: 2,
    meaning: "To move your body in a happy way when music plays.",
    example: "We danced around the room when our favourite song came on.",
    synonyms: ["sway", "boogie", "twirl"], antonyms: ["sit still"] },
  { word: "Deep", pos: "describing word", emoji: "🌊", say: "DEEP", tier: 2,
    meaning: "Going a long way down from the top.",
    example: "The pool was so deep that I could not touch the bottom.",
    synonyms: ["bottomless", "far down"], antonyms: ["shallow"] },
  { word: "Drop", pos: "doing word", emoji: "🤲", say: "DROP", tier: 2,
    meaning: "To let something fall down from your hand.",
    example: "Be careful not to drop the egg on the floor.",
    synonyms: ["fall", "spill", "tumble"], antonyms: ["catch", "lift", "grab"] },
  { word: "Dream", pos: "naming word", emoji: "💭", say: "DREEM", tier: 2,
    meaning: "The pictures and stories you see in your head while you sleep.",
    example: "I had a happy dream about flying over the clouds.",
    synonyms: ["fantasy", "vision"], antonyms: [] },
  { word: "Dizzy", pos: "describing word", emoji: "😵‍💫", say: "DIZ-ee", tier: 2,
    meaning: "Feeling like everything is spinning around you.",
    example: "I felt dizzy after spinning round and round on the grass.",
    synonyms: ["giddy", "wobbly"], antonyms: ["steady", "balanced"] },
  { word: "Delicious", pos: "describing word", emoji: "😋", say: "duh-LISH-us", tier: 3,
    meaning: "Tasting so good that you want more.",
    example: "The warm chocolate cake was absolutely delicious.",
    synonyms: ["yummy", "tasty", "scrumptious"], antonyms: ["yucky", "disgusting"] },
  { word: "Discover", pos: "doing word", emoji: "🔍", say: "diss-KUV-er", tier: 3,
    meaning: "To find something new for the very first time.",
    example: "We discovered a tiny ladybird hiding under the leaf.",
    synonyms: ["find", "uncover", "spot"], antonyms: ["lose", "miss"] },
  { word: "Decide", pos: "doing word", emoji: "🤔", say: "dee-SYDE", tier: 3,
    meaning: "To make up your mind about what you will do.",
    example: "I had to decide whether to wear my red or blue shirt.",
    synonyms: ["choose", "pick", "settle"], antonyms: ["hesitate", "waver"] },
  { word: "Different", pos: "describing word", emoji: "🎨", say: "DIFF-rent", tier: 3,
    meaning: "Not the same as something else.",
    example: "My twin and I like different colours of ice cream.",
    synonyms: ["unlike", "unusual", "varied"], antonyms: ["same", "alike", "similar"] },
  { word: "Dull", pos: "describing word", emoji: "😐", say: "DULL", tier: 3,
    meaning: "Not bright, fun, or exciting at all.",
    example: "The rainy day felt dull until we found a fun board game.",
    synonyms: ["boring", "plain", "drab"], antonyms: ["bright", "exciting", "lively"] },
  { word: "Delightful", pos: "describing word", emoji: "🥰", say: "dee-LITE-ful", tier: 4,
    meaning: "So lovely and pleasing that it makes you smile.",
    example: "We had a delightful picnic in the sunny park.",
    synonyms: ["lovely", "charming", "pleasant"], antonyms: ["unpleasant", "horrible", "dreadful"] },
  { word: "Daring", pos: "describing word", emoji: "🪂", say: "DAIR-ing", tier: 4,
    meaning: "Brave enough to try something bold and exciting.",
    example: "The daring climber went all the way to the top of the wall.",
    synonyms: ["brave", "bold", "fearless"], antonyms: ["timid", "fearful", "shy"] },
  { word: "Devoted", pos: "describing word", emoji: "❤️", say: "dee-VOH-ted", tier: 4,
    meaning: "Loving and caring about someone very, very much.",
    example: "My devoted puppy follows me to every room in the house.",
    synonyms: ["loyal", "loving", "faithful"], antonyms: ["uncaring", "disloyal"] },
  { word: "Doubtful", pos: "describing word", emoji: "🤨", say: "DOWT-ful", tier: 4,
    meaning: "Not sure if something is true or will happen.",
    example: "I was doubtful that the kite would fly with no wind.",
    synonyms: ["unsure", "uncertain"], antonyms: ["certain", "sure", "confident"] },
  { word: "Drowsy", pos: "describing word", emoji: "😴", say: "DROW-zee", tier: 4,
    meaning: "Feeling sleepy and ready to close your eyes.",
    example: "After the long car ride I felt drowsy and yawned.",
    synonyms: ["sleepy", "tired", "weary"], antonyms: ["awake", "alert", "wide-awake"] },
  { word: "Dazzling", pos: "describing word", emoji: "✨", say: "DAZ-ling", tier: 5,
    meaning: "So bright and beautiful that it amazes your eyes.",
    example: "The dazzling fireworks lit up the whole night sky.",
    synonyms: ["sparkling", "brilliant", "gleaming"], antonyms: ["dull", "dim", "drab"] },
  { word: "Diligent", pos: "describing word", emoji: "📚", say: "DIL-i-jent", tier: 5,
    meaning: "Working hard and carefully without giving up.",
    example: "The diligent student checked every answer twice.",
    synonyms: ["hardworking", "careful", "thorough"], antonyms: ["lazy", "careless", "sloppy"] },
  { word: "Dependable", pos: "describing word", emoji: "🤝", say: "dee-PEN-duh-bul", tier: 5,
    meaning: "Always there to help and never lets you down.",
    example: "My dependable friend always keeps the promises she makes.",
    synonyms: ["reliable", "trusty", "steady"], antonyms: ["unreliable", "flaky"] },
  { word: "Drift", pos: "doing word", emoji: "🍃", say: "DRIFT", tier: 5,
    meaning: "To float along slowly and gently with no rush.",
    example: "The little leaf began to drift down the quiet stream.",
    synonyms: ["float", "glide", "wander"], antonyms: ["rush", "speed", "dash"] },
  { word: "Dwindle", pos: "doing word", emoji: "📉", say: "DWIN-dul", tier: 5,
    meaning: "To get smaller and smaller little by little.",
    example: "Our pile of cookies began to dwindle as everyone took one.",
    synonyms: ["shrink", "fade", "lessen"], antonyms: ["grow", "increase", "swell"] },
];

const LETTER_E = [
  { word: "Eat", pos: "doing word", emoji: "🍽️", say: "EET", tier: 1,
    meaning: "To put food in your mouth and swallow it.",
    example: "I like to eat warm chapati with butter.",
    synonyms: ["chew", "munch", "bite"], antonyms: [] },
  { word: "Egg", pos: "naming word", emoji: "🥚", say: "EG", tier: 1,
    meaning: "A smooth oval thing that a baby bird grows inside.",
    example: "Mum cracked an egg into the pan for breakfast.",
    synonyms: ["shell"], antonyms: [] },
  { word: "Ear", pos: "naming word", emoji: "👂", say: "EER", tier: 1,
    meaning: "The part of your body that helps you hear.",
    example: "I covered my ear when the loud bell rang.",
    synonyms: ["lobe"], antonyms: [] },
  { word: "End", pos: "doing word", emoji: "🏁", say: "END", tier: 1,
    meaning: "To finish or come to the last part of something.",
    example: "The story did not end until the dragon fell asleep.",
    synonyms: ["finish", "stop", "close"], antonyms: ["begin", "start"] },
  { word: "Easy", pos: "describing word", emoji: "👌", say: "EE-zee", tier: 1,
    meaning: "Not hard to do at all.",
    example: "Tying my shoes is easy now that I have practised.",
    synonyms: ["simple", "light"], antonyms: ["hard", "difficult", "tricky"] },
  { word: "Empty", pos: "describing word", emoji: "🫙", say: "EMP-tee", tier: 2,
    meaning: "Having nothing inside.",
    example: "My water bottle was empty after the long walk.",
    synonyms: ["bare", "hollow"], antonyms: ["full", "packed", "stuffed"] },
  { word: "Early", pos: "describing word", emoji: "🌅", say: "UR-lee", tier: 2,
    meaning: "Happening before the usual time.",
    example: "We woke up early to catch the school bus.",
    synonyms: ["soon", "ahead"], antonyms: ["late", "tardy"] },
  { word: "Enjoy", pos: "doing word", emoji: "😄", say: "en-JOY", tier: 2,
    meaning: "To feel happy while you do something.",
    example: "I enjoy painting bright flowers with my sister.",
    synonyms: ["like", "love", "relish"], antonyms: ["dislike", "hate"] },
  { word: "Excited", pos: "describing word", emoji: "🤩", say: "ik-SY-tid", tier: 2,
    meaning: "Feeling very happy and full of energy about something fun.",
    example: "I was so excited about my birthday party I could not sit still.",
    synonyms: ["thrilled", "eager", "pumped"], antonyms: ["bored", "calm", "uninterested"] },
  { word: "Elephant", pos: "naming word", emoji: "🐘", say: "EL-uh-funt", tier: 2,
    meaning: "A huge grey animal with big ears and a long trunk.",
    example: "The elephant sprayed water over its back to stay cool.",
    synonyms: ["tusker"], antonyms: [] },
  { word: "Explore", pos: "doing word", emoji: "🧭", say: "ik-SPLOR", tier: 3,
    meaning: "To go and look around a new place to find out about it.",
    example: "We love to explore the little caves near the beach.",
    synonyms: ["search", "discover", "roam"], antonyms: ["ignore"] },
  { word: "Excellent", pos: "describing word", emoji: "🌟", say: "EK-suh-lent", tier: 3,
    meaning: "Very, very good in every way.",
    example: "My teacher said my reading was excellent today.",
    synonyms: ["great", "wonderful", "superb"], antonyms: ["bad", "poor", "terrible"] },
  { word: "Enormous", pos: "describing word", emoji: "🦕", say: "ih-NOR-mus", tier: 3,
    meaning: "Very, very big.",
    example: "The enormous slide was taller than our whole house.",
    synonyms: ["huge", "giant", "massive"], antonyms: ["tiny", "small", "little"] },
  { word: "Encourage", pos: "doing word", emoji: "👏", say: "en-KUR-ij", tier: 3,
    meaning: "To cheer someone on so they feel brave enough to try.",
    example: "My friends encourage me when I race on sports day.",
    synonyms: ["cheer", "support", "inspire"], antonyms: ["discourage"] },
  { word: "Eager", pos: "describing word", emoji: "🙋", say: "EE-gur", tier: 3,
    meaning: "Really wanting to do something right away.",
    example: "The puppy was eager to chase the bouncing ball.",
    synonyms: ["keen", "excited", "ready"], antonyms: ["unwilling", "bored", "reluctant"] },
  { word: "Enthusiastic", pos: "describing word", emoji: "🎉", say: "in-THOO-zee-AS-tik", tier: 4,
    meaning: "Showing lots of happy excitement about something.",
    example: "She gave an enthusiastic cheer when our team scored.",
    synonyms: ["eager", "excited", "keen"], antonyms: ["bored", "uninterested", "dull"] },
  { word: "Enchanting", pos: "describing word", emoji: "✨", say: "in-CHAN-ting", tier: 4,
    meaning: "So lovely and magical that you cannot look away.",
    example: "The enchanting garden was full of glowing fireflies.",
    synonyms: ["magical", "charming", "lovely"], antonyms: ["dull", "boring", "plain"] },
  { word: "Examine", pos: "doing word", emoji: "🔍", say: "ig-ZAM-in", tier: 4,
    meaning: "To look at something very closely to learn about it.",
    example: "The doctor used a light to examine my sore throat.",
    synonyms: ["inspect", "study", "check"], antonyms: ["ignore", "overlook"] },
  { word: "Effort", pos: "naming word", emoji: "💪", say: "EF-urt", tier: 4,
    meaning: "The hard work and trying you put into something.",
    example: "She put a lot of effort into her colourful drawing.",
    synonyms: ["work", "trying", "struggle"], antonyms: ["laziness", "ease"] },
  { word: "Energetic", pos: "describing word", emoji: "⚡", say: "en-ur-JET-ik", tier: 4,
    meaning: "Full of energy and ready to run and play.",
    example: "After breakfast I felt energetic enough to dance all morning.",
    synonyms: ["lively", "active", "peppy"], antonyms: ["tired", "sleepy", "lazy"] },
  { word: "Exquisite", pos: "describing word", emoji: "💎", say: "ik-SKWIZ-it", tier: 5,
    meaning: "So beautifully made that it feels very special.",
    example: "Grandma's exquisite necklace sparkled like tiny stars.",
    synonyms: ["beautiful", "lovely", "fine"], antonyms: ["plain", "ugly", "rough"] },
  { word: "Exhilarating", pos: "describing word", emoji: "🎢", say: "ig-ZIL-uh-ray-ting", tier: 5,
    meaning: "So thrilling that it makes your heart race with joy.",
    example: "The exhilarating roller coaster made us all squeal with delight.",
    synonyms: ["thrilling", "exciting", "electrifying"], antonyms: ["boring", "dull", "calming"] },
  { word: "Eloquent", pos: "describing word", emoji: "🗣️", say: "EL-uh-kwent", tier: 5,
    meaning: "Speaking in a clear and beautiful way that people love to hear.",
    example: "Her eloquent speech about kindness made the whole class clap.",
    synonyms: ["well-spoken", "fluent", "expressive"], antonyms: ["mumbling", "tongue-tied"] },
  { word: "Endeavour", pos: "doing word", emoji: "🧗", say: "en-DEV-ur", tier: 5,
    meaning: "To try very hard to do something difficult.",
    example: "We endeavour to plant a tree in our garden every year.",
    synonyms: ["try", "strive", "attempt"], antonyms: ["quit", "give up"] },
  { word: "Exuberant", pos: "describing word", emoji: "🥳", say: "ig-ZOO-bur-unt", tier: 5,
    meaning: "Bursting with happiness and lively cheer.",
    example: "The exuberant crowd jumped and sang when the parade arrived.",
    synonyms: ["joyful", "lively", "bubbly"], antonyms: ["gloomy", "dull", "sad"] },
];

const LETTER_F = [
  { word: "Fast", pos: "describing word", emoji: "🏃", say: "FAST", tier: 1,
    meaning: "Moving very quickly in a short time.",
    example: "My puppy is so fast that I can't catch him!",
    synonyms: ["quick", "speedy", "rapid"], antonyms: ["slow", "sluggish"] },
  { word: "Fish", pos: "naming word", emoji: "🐟", say: "FISH", tier: 1,
    meaning: "An animal that lives and swims in the water.",
    example: "A shiny orange fish swam round and round its bowl.",
    synonyms: ["sea animal"], antonyms: [] },
  { word: "Fun", pos: "describing word", emoji: "😄", say: "FUN", tier: 1,
    meaning: "Something that makes you feel happy and full of joy.",
    example: "Playing in the park with my friends is so much fun.",
    synonyms: ["enjoyable", "playful", "jolly"], antonyms: ["boring", "dull"] },
  { word: "Fly", pos: "doing word", emoji: "🦋", say: "FLY", tier: 1,
    meaning: "To move through the air with wings.",
    example: "I watched a little bird fly over our roof.",
    synonyms: ["soar", "glide", "flutter"], antonyms: ["land"] },
  { word: "Frog", pos: "naming word", emoji: "🐸", say: "FROG", tier: 1,
    meaning: "A small green animal that hops and lives near water.",
    example: "The green frog jumped from the leaf into the pond.",
    synonyms: ["toad"], antonyms: [] },
  { word: "Friend", pos: "naming word", emoji: "🧑‍🤝‍🧑", say: "FREND", tier: 2,
    meaning: "Someone you like who likes you and plays with you.",
    example: "My best friend shared her crayons with me at school.",
    synonyms: ["pal", "buddy", "mate"], antonyms: ["enemy"] },
  { word: "Funny", pos: "describing word", emoji: "😂", say: "FUH-nee", tier: 2,
    meaning: "Something that makes you laugh and giggle.",
    example: "The clown made a funny face and everyone laughed.",
    synonyms: ["amusing", "silly", "hilarious"], antonyms: ["serious", "sad"] },
  { word: "Fresh", pos: "describing word", emoji: "🥬", say: "FRESH", tier: 2,
    meaning: "New and clean, not old or stale.",
    example: "Grandma picked fresh tomatoes from her garden.",
    synonyms: ["new", "crisp", "clean"], antonyms: ["stale", "old"] },
  { word: "Fix", pos: "doing word", emoji: "🔧", say: "FIKS", tier: 2,
    meaning: "To make something work again after it breaks.",
    example: "Dad helped me fix the wheel on my toy car.",
    synonyms: ["mend", "repair", "patch"], antonyms: ["break", "damage"] },
  { word: "Float", pos: "doing word", emoji: "🎈", say: "FLOHT", tier: 2,
    meaning: "To stay up on top of water or in the air.",
    example: "My red boat can float across the bathtub.",
    synonyms: ["drift", "bob"], antonyms: ["sink"] },
  { word: "Friendly", pos: "describing word", emoji: "😊", say: "FREND-lee", tier: 3,
    meaning: "Kind, warm, and nice to be around.",
    example: "The friendly new boy waved hello to everyone.",
    synonyms: ["kind", "warm", "nice"], antonyms: ["mean", "unkind"] },
  { word: "Famous", pos: "describing word", emoji: "⭐", say: "FAY-mus", tier: 3,
    meaning: "Known and liked by lots and lots of people.",
    example: "The famous singer waved at the cheering crowd.",
    synonyms: ["well-known", "popular"], antonyms: ["unknown"] },
  { word: "Fancy", pos: "describing word", emoji: "💃", say: "FAN-see", tier: 3,
    meaning: "Very pretty and special, not plain or simple.",
    example: "She wore a fancy dress with sparkles to the party.",
    synonyms: ["elegant", "posh", "grand"], antonyms: ["plain", "simple"] },
  { word: "Fold", pos: "doing word", emoji: "🧺", say: "FOHLD", tier: 3,
    meaning: "To bend something over so it becomes smaller and neat.",
    example: "I helped Mum fold the warm towels into neat squares.",
    synonyms: ["crease", "bend", "tuck"], antonyms: ["unfold", "spread"] },
  { word: "Forget", pos: "doing word", emoji: "🤔", say: "for-GET", tier: 3,
    meaning: "To not remember something you knew before.",
    example: "Don't forget to take your lunch box to school!",
    synonyms: ["miss", "overlook"], antonyms: ["remember", "recall"] },
  { word: "Fragile", pos: "describing word", emoji: "🥚", say: "FRAJ-ul", tier: 4,
    meaning: "So delicate that it breaks very easily.",
    example: "Hold the fragile egg gently so it doesn't crack.",
    synonyms: ["delicate", "breakable"], antonyms: ["strong", "tough"] },
  { word: "Faithful", pos: "describing word", emoji: "🐕", say: "FAYTH-ful", tier: 4,
    meaning: "Always there for you and never letting you down.",
    example: "My faithful dog waits by the door every day.",
    synonyms: ["loyal", "true", "devoted"], antonyms: ["disloyal", "untrue"] },
  { word: "Forgive", pos: "doing word", emoji: "🤗", say: "for-GIV", tier: 4,
    meaning: "To stop being upset with someone who said sorry.",
    example: "I forgive my brother for breaking my toy.",
    synonyms: ["pardon", "excuse"], antonyms: ["blame", "punish"] },
  { word: "Fortunate", pos: "describing word", emoji: "🍀", say: "FOR-chuh-nut", tier: 4,
    meaning: "Very lucky to have good things happen to you.",
    example: "I am fortunate to have such a loving family.",
    synonyms: ["lucky", "blessed"], antonyms: ["unlucky", "unfortunate"] },
  { word: "Fierce", pos: "describing word", emoji: "🐯", say: "FEERS", tier: 4,
    meaning: "Very strong, bold, and powerful.",
    example: "The fierce tiger let out a loud, mighty roar.",
    synonyms: ["bold", "strong", "wild"], antonyms: ["gentle", "timid"] },
  { word: "Fascinating", pos: "describing word", emoji: "🔬", say: "FAS-uh-nay-ting", tier: 5,
    meaning: "So interesting that you cannot stop looking or learning.",
    example: "The fascinating book about space kept me reading all night.",
    synonyms: ["interesting", "captivating", "gripping"], antonyms: ["boring", "dull"] },
  { word: "Flourish", pos: "doing word", emoji: "🌱", say: "FLUR-ish", tier: 5,
    meaning: "To grow well and become healthy and strong.",
    example: "My little plant began to flourish in the sunny window.",
    synonyms: ["thrive", "grow", "bloom"], antonyms: ["wither", "fade"] },
  { word: "Fearless", pos: "describing word", emoji: "🦁", say: "FEER-lus", tier: 5,
    meaning: "Brave and not scared of anything at all.",
    example: "The fearless little girl climbed to the top of the tree.",
    synonyms: ["brave", "bold", "daring"], antonyms: ["afraid", "scared", "timid"] },
  { word: "Flexible", pos: "describing word", emoji: "🤸", say: "FLEK-suh-bul", tier: 5,
    meaning: "Able to bend easily without breaking.",
    example: "A gymnast is so flexible she can touch her toes easily.",
    synonyms: ["bendy", "supple", "stretchy"], antonyms: ["stiff", "rigid"] },
  { word: "Flabbergasted", pos: "describing word", emoji: "😲", say: "FLAB-er-gas-tid", tier: 5,
    meaning: "So surprised that you don't know what to say.",
    example: "I was flabbergasted when I saw the giant birthday cake!",
    synonyms: ["amazed", "astonished", "stunned"], antonyms: ["calm", "unsurprised"] },
];

